spring:
  application:
    name: pass-web
  datasource:
    url: jdbc:mysql://localhost:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useCursorFetch=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false